homework 3
flogea/2024-2-VK-EDU-Frontend-E-Logvinova pull request #4
Opened 2024-10-16 21:47 UTC by flogea

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* декомпозиция проекта
* вёрстка главной страницы
* кнопка создания чата с плавной анимашкой

2024-10-18 17:21 UTC, RomanBarannickov requested changes
1. Пока ок, но должно быть полноценное добавление нового чата
2. должен работать поиск по чатам
3. если не используем this внутри функции и остальные фишки, или это не метод внутри класса, предпочтительнее использовать стрелочные функции
4. именование с большой буквы принято только для классов, понимаю, что похоже на компоненты реакт и все такое, но у нас в данный момент не реакт. Исправлять не надо, но подсвечиваю важность этой договороненности
5. Странное поведение, если указать на странице чата несуществующий id чата, выдает последний найденный чат. Как воспроизвести
- зайти на демо
- выбрать чат
- на выбранной странице чата, перейти в url и поменять id на несуществующий

2024-10-18 17:21 UTC, RomanBarannickov commented on simple-chat/src/utils/navigation.js
> +  }
можно без else написать

2024-10-18 17:21 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +window.addEventListener('popstate', handleRouteChange);
интересное решение, но
1. не увидел явного использования history API для вызова этого события
2. расскажи для чего эта подписка здесь?

2024-10-27 17:34 UTC, martinkomitsky commented
@flogea привет! получится довести до апрува замечания от ментора?

2024-10-27 17:37 UTC, flogea commented
> @flogea привет! получится довести до апрува замечания от ментора?

Мне осталось доделать одно замечание, надеюсь сделать его в течение пары дней 🥺

2024-10-27 17:43 UTC, martinkomitsky commented
> > @flogea привет! получится довести до апрува замечания от ментора?
> 
> Мне осталось доделать одно замечание, надеюсь сделать его в течение пары дней 🥺

отличные новости! очень ждём) не забудь потом влить эти изменения после мержа в ветку ДЗ 4 и починить появившиеся там конфликты

2024-10-28 13:11 UTC, flogea commented on simple-chat/src/index.js
> +window.addEventListener('popstate', handleRouteChange);
я отслеживаю изменения в url, у меня есть навигация по страницам в utils navigation.js, я подумала, что будет правильней вынести рендеринг страниц в корневой файл

2024-10-30 09:21 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув
 
 @flogea все круто. Добавление чата просто бомба!
 просто обращаю внимание на следующие моменты. Некоторые из них носят исключительно рекомендательный характер
 1. кнопка добавление чата прям сильно к правому краю находится. Сделай отступ по больше
 2. когда добавляется новый чат и в нем ничего не написать, то на месте последнего сообщения выводиться "undefined"
 3. в модалке добавления нового чата не должны быть предложены друзья с которыми уже есть чаты
 4. при добавление сообщения в чат начинает появляться с боку скролл сразу. Лучше контейнер сообщений сразу растягивать на всю высоту и потом уже когда действительно пойдет переполнение, он появится
 5. можно застилизовать и скролл, чтоб он так сильно не выделялся в темной теме
 6. По структуре объекта message - в поле sender нужно указывать не имя с кем чат, а своё имя, а лучше не имя, а айди на самого себя любимого
 7. при входе на страницу чата, хотелось бы сразу получать фокус на поле ввода

2024-10-30 11:02 UTC, flogea commented
>  3. в модалке добавления нового чата не должны быть предложены друзья с которыми уже есть чаты

Со всем согласна, спасибо большое, но справедливости ради, по этому пункту и в ВК, и в телеге про создании чата можно выбрать людей, с кем чаты существуют. Возможно, по UX просто было бы правильнее написать не "создать чат", а что-то другое, типа "начать чат"

2024-10-30 11:58 UTC, RomanBarannickov commented
согласен с резонным замечанием по поводу добавление чата

2024-10-31 06:33 UTC, HaseProgram approved these changes
Зачтено, 7!

2024-10-31 06:33 UTC, merged